version: "3.7"

services:
  redis:
    container_name: "redis"
    image: "bitnami/redis:latest"
    environment:
      REDIS_PASSWORD: password123
    expose:
      - 6379
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - inetwork
    restart: unless-stopped
  
  redisinsight:
    container_name: redis-insight
    image: redis/redisinsight:latest
    restart: always
    ports:
    - "127.0.0.1:5540:5540"
    networks:
    - inetwork

networks:
  inetwork:
    external: true 
    name: inetwork
